#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_fixtures.py -- deterministically generate all oracle test fixtures.

Usage:
    python tests/gen_fixtures.py [--force]

Fixtures produced in tests/fixtures/:
  good.txt         valid UTF-8 text, no PII
  bad_empty.txt    0 bytes
  bad_encoding.txt GBK bytes (strict UTF-8 decode must fail)
  pii.txt          line 2 has a CN mobile, line 3 has an 18-digit CN ID,
                   line 4 has a landline that must NOT hit
  clean.docx       generated with python-docx (1 heading + 1 paragraph)
  corrupt.docx     .docx extension but garbage content (python-docx must fail)

The fixture writer is content-addressed: files are rewritten only when missing
or when their bytes differ, so reruns are idempotent.
"""
import sys
from pathlib import Path

FIX = Path(__file__).resolve().parent / "fixtures"


def build_docx(path: Path) -> bytes:
    from docx import Document

    doc = Document()
    doc.add_heading("Oracle self-test document", level=1)
    doc.add_paragraph("Generated by python-docx to prove the .docx openability check.")
    doc.save(str(path))
    return path.read_bytes()


def ensure_fixtures(force: bool = False):
    FIX.mkdir(parents=True, exist_ok=True)

    good = ("sample deliverable: this is a normal output file.\n"
            "two lines, UTF-8, no phone number and no ID number.\n").encode("utf-8")
    gbk = "本文件按 GBK 编码写入，严格 UTF-8 解码必须失败。".encode("gbk")
    pii = ("test contact list\n"
           "zhangsan mobile 13812345678\n"
           "lisi id-number 110101199003074258\n"
           "wangwu landline 010-62771234 (must not hit)\n").encode("utf-8")
    corrupt = b"this is definitely not a zip package\r\n"

    plan = {
        "good.txt": good,
        "bad_empty.txt": b"",
        "bad_encoding.txt": gbk,
        "pii.txt": pii,
        "corrupt.docx": corrupt,
    }
    for name, data in plan.items():
        p = FIX / name
        if force or not p.exists() or p.read_bytes() != data:
            p.write_bytes(data)

    # clean.docx: always rebuilt (cheap, and keeps the artifact fresh)
    build_docx(FIX / "clean.docx")

    # sanity assertions on the fixtures themselves
    assert len("110101199003074258") == 18, "fixture ID must be 18 digits"
    try:
        gbk.decode("utf-8")
        raise AssertionError("bad_encoding.txt must NOT be valid UTF-8")
    except UnicodeDecodeError:
        pass

    return sorted(p.name for p in FIX.iterdir())


if __name__ == "__main__":
    force = "--force" in sys.argv
    names = ensure_fixtures(force=force)
    print("fixtures ready in %s:" % FIX)
    for n in names:
        print("  " + n)
