#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""tests/gen_fixtures.py -- 幂等生成 6 个测试 fixtures（contract.md §1 / spec R4.1）。

用法：
    python tests/gen_fixtures.py [--force]    # exit 0；幂等

规则：
  - 文本 fixtures（good/bad_empty/bad_encoding/pii/corrupt）content-addressed：
    缺失或字节不同才重写（--force 强制全部重写），重复执行字节不变 => 幂等。
  - clean.docx 每次都用 python-docx 重建（contract：每次重建）。
  - 生成后自断言：pii.txt 恰含 1 个 18 位身份证（长度=18）与 1 个 CN 手机号；
    bad_encoding.txt 的 GBK 字节在严格 UTF-8 解码下必须失败。
"""
import re
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"

GOOD_TXT = (
    "交付说明（示例文档）\n"
    "本文为UTF-8纯文本样例，用于验证产物校验与PII扫描的放行路径。\n"
).encode("utf-8")

BAD_EMPTY_TXT = b""

# GBK 字节：严格 UTF-8 解码必须失败（供 validate_output 阻断 / pii_guard fail-open 用）
BAD_ENCODING_TXT = "机密：内部资料，请勿外传\n".encode("gbk")

# 第 2 行 CN 手机、第 3 行 18 位身份证、第 4 行座机（不得命中）（contract §1）
PII_TXT = (
    "客户回访记录（内部测试样例，非真实数据）\n"
    "联系手机：13812345678\n"
    "身份证号：110101199003074258\n"
    "办公座机：021-62881230（不应命中）\n"
).encode("utf-8")

# .docx 后缀的垃圾字节：python-docx 必须打不开（contract §1）
CORRUPT_DOCX = b"this is not a zip archive; deliberately corrupt bytes for .docx\n"

TEXT_FIXTURES = {
    "good.txt": GOOD_TXT,
    "bad_empty.txt": BAD_EMPTY_TXT,
    "bad_encoding.txt": BAD_ENCODING_TXT,
    "pii.txt": PII_TXT,
    "corrupt.docx": CORRUPT_DOCX,
}


def write_if_changed(path, data, force):
    """content-addressed 写：缺失或字节不同（或 --force）才写。返回是否写入。"""
    if not force and path.is_file():
        try:
            if path.read_bytes() == data:
                return False
        except OSError:
            pass
    path.write_bytes(data)
    return True


def build_clean_docx():
    """clean.docx 每次重建：python-docx 可打开的有效文档。"""
    from docx import Document

    doc = Document()
    doc.add_heading("Clean fixture", level=1)
    doc.add_paragraph("This is a valid .docx fixture generated by tests/gen_fixtures.py.")
    doc.save(str(FIXTURE_DIR / "clean.docx"))


def self_check():
    """生成后自断言（spec R4.1）。"""
    pii_text = PII_TXT.decode("utf-8")
    ids = re.findall(r"(?<!\d)\d{17}[\dXx](?!\d)", pii_text)
    assert len(ids) == 1, "pii.txt must contain exactly one 18-digit CN id, got %d" % len(ids)
    assert len(ids[0]) == 18, "cn-id fixture must be 18 chars, got %d" % len(ids[0])
    phones = re.findall(r"(?<!\d)1[3-9]\d{9}(?!\d)", pii_text)
    assert len(phones) == 1, "pii.txt must contain exactly one CN mobile, got %d" % len(phones)
    try:
        BAD_ENCODING_TXT.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        pass
    else:
        raise AssertionError("bad_encoding.txt bytes must fail strict UTF-8 decoding")


def main(argv):
    force = "--force" in argv
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    rewritten = []
    for name, data in TEXT_FIXTURES.items():
        if write_if_changed(FIXTURE_DIR / name, data, force):
            rewritten.append(name)
    build_clean_docx()
    self_check()

    # 终检：6 个 fixture 就位；bad_empty 为 0 字节；其余非空
    expected = ["good.txt", "bad_empty.txt", "bad_encoding.txt",
                "pii.txt", "clean.docx", "corrupt.docx"]
    for name in expected:
        p = FIXTURE_DIR / name
        if not p.is_file():
            print("gen_fixtures: FAIL: %s missing after generation" % name, file=sys.stderr)
            return 1
        size = p.stat().st_size
        if name == "bad_empty.txt" and size != 0:
            print("gen_fixtures: FAIL: bad_empty.txt must be 0 bytes, got %d" % size, file=sys.stderr)
            return 1
        if name != "bad_empty.txt" and size == 0:
            print("gen_fixtures: FAIL: %s must not be empty" % name, file=sys.stderr)
            return 1

    print("gen_fixtures: OK: 6 fixtures ready in %s%s"
          % (FIXTURE_DIR, (" (rewrote: %s)" % ", ".join(rewritten)) if rewritten else " (all up-to-date; clean.docx rebuilt)"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
